# Use the latest stable version of Debian
FROM debian:stable

# Create the vscode user
RUN useradd -ms /bin/bash vscode

# Update the package list and install any necessary packages
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    # Add any packages you need here
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Zsh and Oh My Zsh
RUN apt-get update && apt-get install -y zsh wget git \
    && sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    && chsh -s $(which zsh) \

    && apt-get install -y locales locales-all \
    && update-locale

# Set up Oh My Zsh with a theme and plugins
RUN rm -rf /home/vscode/.oh-my-zsh \
    && git clone https://github.com/powerline/fonts.git \
    && cd fonts \
    && ./install.sh \
    && cd .. && rm -rf fonts \
    && git clone https://github.com/ohmyzsh/ohmyzsh.git /home/vscode/.oh-my-zsh \
    && cp /home/vscode/.oh-my-zsh/templates/zshrc.zsh-template /home/vscode/.zshrc \
    && sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/' /home/vscode/.zshrc \
    && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-/home/vscode/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting \
    && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-/home/vscode/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
    && sed -i 's/plugins=(git)/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/' /home/vscode/.zshrc

# Switch to vscode user
USER vscode

# Download and install Rust using rustup
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Set the environment variables for Rust
ENV PATH="/home/vscode/.cargo/bin:${PATH}"

# Verify the installation
RUN /home/vscode/.cargo/bin/rustc --version && /home/vscode/.cargo/bin/cargo --version

# Set the default shell to Zsh
SHELL ["/usr/bin/zsh", "-c"]

# Set the working directory
WORKDIR /workspace

# Specify the command to run the application
CMD ["zsh"]
